In this notebook we will be covering some of the most fundamental concepts of tensors using Tensorflow


##Introduction to Tensors


In [12]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)


2.12.0


Syntax for the tf.constant:
tf.constant(value, dtype=None, shape=None, name='Const')

Use case:
Creates a constant tensor from a tensor-like object.

In [13]:
#Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [14]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [15]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [16]:
#check the dimension
vector.ndim

1

In [17]:
#create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [18]:
#check the dimension
matrix.ndim

2

In [19]:
#Create another matrix 
another_matrix = tf.constant([[10., 7.],[3.,2.],[8., 9.]],dtype=tf.float16)
#specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [20]:
#number of dimension
another_matrix.ndim

2

In [21]:
 #create a tensor 
tensor = tf.constant([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [22]:
#number of dimension
tensor.ndim

3

type      ndim

1.  Scalar-   0
2.  Vector-   1
3.  Matrix-   2
4.  Tensor-   3







*Scalar: a single number

*Vector: a number with a direction 


*Matrix:  a 2-dimensional array of numbers 


*Tensor: an n-dimensional array of numbers

###Creating tf.Variable

In [23]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [24]:
#Same tensor
changable_tensor= tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [25]:
#changing one of the element in changeable_tensor
changable_tensor[0] = 7
changable_tensor



TypeError: ignored

In [26]:
#How about we try .assign
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [27]:
#unchangeable_tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [28]:
# variable tensor -> tf.Variable
# non variable ->tf.constant

##Creating Random Tensors

In [29]:
from tensorflow._api.v2 import random
#Random tensors are tensors of some abitrary size which contain random number 
ran1= tf.random.Generator.from_seed(42)# set seed for reproducibility
ran1= random.normal(shape=(3,2))
ran1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.6657276 , -0.00234972],
       [ 0.51344705, -1.2771568 ],
       [-1.4592905 , -1.4009794 ]], dtype=float32)>

In [30]:
ran1= tf.random.Generator.from_seed(42)# set seed for reproducibility
ran1= ran1.normal(shape=(3,2))
ran2 = tf.random.Generator.from_seed(42)
ran2 = ran2.normal(shape=(3,2))
ran1,ran2, ran1==ran2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [47]:
#They are sudo random numbers

In [31]:
#When the value passed as the parameter to the function for generating the random variable changes then the 2 random variables will not be same as it is sudo random numbers
ran1= tf.random.Generator.from_seed(7)# set seed for reproducibility
ran1= ran1.normal(shape=(3,2))
ran2 = tf.random.Generator.from_seed(42)
ran2 = ran2.normal(shape=(3,2))
ran1,ran2, ran1==ran2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

##Shuffling the order of the elements in a tensor

In [33]:
#shuffling the order of elements in a tensor
#it is required because the dataset is not the way we want it to be 
#so that the inherent order doesn't effect learning
not_shuffle = tf.constant([[10,7],[3,4],[2,5]])
not_shuffle.ndim

2

In [36]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [37]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [38]:
not_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [39]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [40]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [41]:
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [42]:
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [43]:
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [44]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [45]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffle, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [46]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>


*It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as operation level random seed:*
>Rule 4:"If both the global and operation seed are set: Both seeds are used in conjunction to determine the random sequence." 

In [48]:
#Other ways to make tensors
#numpy.ones
#tf.ones

#Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [49]:
#Create a tensor of all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [50]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [51]:
#You can also turn Numpy arrays into tensors

### Turn Numpy arrays into tensors 

The main difference between the Numpy arrays and tensorflow tensors is that tensors can be run on gpu much faster for numerical computing 

In [52]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A
#Create a numpy array between 1-25
# X = tf.constant(some_matrix) # Capital for matrix or tensor
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [53]:
A = tf.constant(numpy_A)

In [54]:
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [55]:
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [56]:
2*3*4

24

In [57]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [58]:
A = tf.constant(numpy_A,shape=(2,3,5))
A

TypeError: ignored

In [59]:
A = tf.constant(numpy_A,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [60]:
3*8

24

### Getting Information from the tensors

*shape
rank 
axis or dimension
size